### ISSUE TITLE
Using an Option column with a non-Option in a Setter throws an Exception

### ISSUE THREAD

**Issue by brendanator** [jhc-systems/sqlest#49]
```
java.lang.ClassCastException: java.lang.String cannot be cast to scala.Option 
at sqlest.executor.Session.sqlest$executor$Session$$setArgument(Database.scala:140) 
at sqlest.executor.Session$$anonfun$sqlest$executor$Session$$innerSetArguments$1$1.apply(Database.scala:118) 
at sqlest.executor.Session$$anonfun$sqlest$executor$Session$$innerSetArguments$1$1.apply(Database.scala:116) 
at scala.collection.immutable.List.foreach(List.scala:381) 
at sqlest.executor.Session.sqlest$executor$Session$$innerSetArguments$1(Database.scala:116) 
at sqlest.executor.Session$$anonfun$setArguments$1.apply(Database.scala:124) 
at sqlest.executor.Session$$anonfun$setArguments$1.apply(Database.scala:123) 
at scala.collection.immutable.List.foreach(List.scala:381) 
at sqlest.executor.Session.setArguments(Database.scala:122) 
at sqlest.executor.Session.prepareStatement(Database.scala:109) 
at sqlest.executor.Transaction$$anonfun$executeCommand$1.apply(Database.scala:209) 
at sqlest.executor.Transaction$$anonfun$executeCommand$1.apply(Database.scala:205) 
at sqlest.executor.Transaction.withConnection(Database.scala:181) 
at sqlest.executor.Transaction.executeCommand(Database.scala:205) 
```

**Comment by brendanator** [comment]
Fixed by 626c62411b
